[package]
name = "monkelang"
version = "0.1.0"
authors = ["Trijavico <javier.penaperez08@gmail.com>"]
edition = "2021"

[lib]
crate-type=["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.87"
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.72", features = ["Window", "Document", "HtmlElement"] }
